var hierarchy =
[
    [ "any", "structtapkee_1_1any.html", null ],
    [ "arpack_wrapper< Scalar, RealScalar >", "structarpack__internal_1_1arpack__wrapper.html", null ],
    [ "arpack_wrapper< double, double >", "structarpack__internal_1_1arpack__wrapper_3_01double_00_01double_01_4.html", null ],
    [ "arpack_wrapper< float, float >", "structarpack__internal_1_1arpack__wrapper_3_01float_00_01float_01_4.html", null ],
    [ "ArpackGeneralizedSelfAdjointEigenSolver< LMatrixType, RMatrixType, MatrixOperation, BisSPD >", "classArpackGeneralizedSelfAdjointEigenSolver.html", null ],
    [ "bad_any_cast", "structtapkee_1_1anyimpl_1_1bad__any__cast.html", null ],
    [ "base_any_policy", "structtapkee_1_1anyimpl_1_1base__any__policy.html", [
      [ "typed_base_any_policy< T >", "structtapkee_1_1anyimpl_1_1typed__base__any__policy.html", [
        [ "big_any_policy< T >", "structtapkee_1_1anyimpl_1_1big__any__policy.html", null ],
        [ "small_any_policy< T >", "structtapkee_1_1anyimpl_1_1small__any__policy.html", null ]
      ] ]
    ] ],
    [ "BasicCallbackTraits< Callback >", "structBasicCallbackTraits.html", null ],
    [ "BatchCallbackTraits< Callback >", "structBatchCallbackTraits.html", null ],
    [ "Cell", "classtsne_1_1Cell.html", null ],
    [ "choose_policy< T >", "structtapkee_1_1anyimpl_1_1choose__policy.html", null ],
    [ "choose_policy< any >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01any_01_4.html", null ],
    [ "choose_policy< bool >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01bool_01_4.html", null ],
    [ "choose_policy< float >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01float_01_4.html", null ],
    [ "choose_policy< signed char >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01signed_01char_01_4.html", null ],
    [ "choose_policy< signed int >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01signed_01int_01_4.html", null ],
    [ "choose_policy< signed long >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01signed_01long_01_4.html", null ],
    [ "choose_policy< signed short >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01signed_01short_01_4.html", null ],
    [ "choose_policy< T * >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01T_01_5_01_4.html", null ],
    [ "choose_policy< unsigned char >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01unsigned_01char_01_4.html", null ],
    [ "choose_policy< unsigned int >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01unsigned_01int_01_4.html", null ],
    [ "choose_policy< unsigned long >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01unsigned_01long_01_4.html", null ],
    [ "choose_policy< unsigned short >", "structtapkee_1_1anyimpl_1_1choose__policy_3_01unsigned_01short_01_4.html", null ],
    [ "CoverTreePoint< RandomAccessIterator >", "structtapkee_1_1tapkee__internal_1_1CoverTreePoint.html", null ],
    [ "d_node< P >", "structtapkee_1_1tapkee__internal_1_1d__node.html", null ],
    [ "DataPoint", "classtsne_1_1DataPoint.html", null ],
    [ "DenseImplicitSquareMatrixOperation", "structtapkee_1_1tapkee__internal_1_1DenseImplicitSquareMatrixOperation.html", null ],
    [ "DenseInverseMatrixOperation", "structtapkee_1_1tapkee__internal_1_1DenseInverseMatrixOperation.html", null ],
    [ "DenseMatrixOperation", "structtapkee_1_1tapkee__internal_1_1DenseMatrixOperation.html", null ],
    [ "distance_callback", "structdistance__callback.html", null ],
    [ "VpTree< T, distance >::DistanceComparator", "structtsne_1_1VpTree_1_1DistanceComparator.html", null ],
    [ "distances_comparator< DistanceRecord >", "structtapkee_1_1tapkee__internal_1_1distances__comparator.html", null ],
    [ "ds_node< P >", "structtapkee_1_1tapkee__internal_1_1ds__node.html", null ],
    [ "eigen_embedding_impl< MatrixType, MatrixOperationType, IMPLEMENTATION >", "structtapkee_1_1tapkee__internal_1_1eigen__embedding__impl.html", null ],
    [ "eigen_embedding_impl< MatrixType, MatrixOperationType, ARPACK >", "structtapkee_1_1tapkee__internal_1_1eigen__embedding__impl_3_01MatrixType_00_01MatrixOperationType_00_01ARPACK_01_4.html", null ],
    [ "eigen_embedding_impl< MatrixType, MatrixOperationType, EIGEN_DENSE_SELFADJOINT_SOLVER >", "structtapkee_1_1tapkee__internal_1_1eigen__embedding__impl_3_01MatrixType_00_01MatrixOperationTy70072b449273c2bd9a9fbeb5ecbaa247.html", null ],
    [ "eigen_embedding_impl< MatrixType, MatrixOperationType, RANDOMIZED >", "structtapkee_1_1tapkee__internal_1_1eigen__embedding__impl_3_01MatrixType_00_01MatrixOperationType_00_01RANDOMIZED_01_4.html", null ],
    [ "eigendecomposition_error", "classtapkee_1_1eigendecomposition__error.html", null ],
    [ "empty_any", "structtapkee_1_1anyimpl_1_1empty__any.html", null ],
    [ "ezOptionParser", "classez_1_1ezOptionParser.html", null ],
    [ "ezOptionParserIDGenerator", "classez_1_1ezOptionParserIDGenerator.html", null ],
    [ "ezOptionValidator", "classez_1_1ezOptionValidator.html", null ],
    [ "feature_vector_callback", "structfeature__vector__callback.html", null ],
    [ "FibonacciHeap", "classtapkee_1_1tapkee__internal_1_1FibonacciHeap.html", null ],
    [ "FibonacciHeapNode", "structtapkee_1_1tapkee__internal_1_1FibonacciHeapNode.html", null ],
    [ "generalized_eigen_embedding_impl< LMatrixType, RMatrixType, MatrixOperationType, IMPLEMENTATION >", "structtapkee_1_1tapkee__internal_1_1generalized__eigen__embedding__impl.html", null ],
    [ "generalized_eigen_embedding_impl< LMatrixType, RMatrixType, MatrixOperationType, ARPACK >", "structtapkee_1_1tapkee__internal_1_1generalized__eigen__embedding__impl_3_01LMatrixType_00_01RMa86dacd6ba6a78c0dc7b4e29ccd544538.html", null ],
    [ "generalized_eigen_embedding_impl< LMatrixType, RMatrixType, MatrixOperationType, EIGEN_DENSE_SELFADJOINT_SOLVER >", "structtapkee_1_1tapkee__internal_1_1generalized__eigen__embedding__impl_3_01LMatrixType_00_01RMa63f40aab8e6a207043f456b8204db28b.html", null ],
    [ "VpTree< T, distance >::HeapItem", "structtsne_1_1VpTree_1_1HeapItem.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, IMPLEMENTATION >", "structtapkee_1_1tapkee__internal_1_1implementation.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, DIFFUSION_MAP >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_6811a0bcfaaf65cdb08b7d6dcd289bd7.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, FACTOR_ANALYSIS >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_210aaffcf701147e4ab26af3f87e4390.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, HESSIAN_LOCALLY_LINEAR_EMBEDDING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_d818db016514c8829224f33df7da7cf8.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, ISOMAP >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_11ebd743657c1f28f4dd1189f38a5fb3.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, KERNEL_LOCAL_TANGENT_SPACE_ALIGNMENT >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_72a0e5cc20e6c1b925c447125d40e92f.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, KERNEL_LOCALLY_LINEAR_EMBEDDING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_225e7a8ffaebf500ca8dc718e1d8fa53.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, KERNEL_PCA >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_65532e178dfccf712d7220a1e6dce83c.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, LANDMARK_ISOMAP >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_4931f4632f27bb5d638ab1f1a3fcd410.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, LANDMARK_MULTIDIMENSIONAL_SCALING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_776d2cd9f30454c54aa322af0a644365.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, LAPLACIAN_EIGENMAPS >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_40825060ade8dd11f968143bd3f38546.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, LINEAR_LOCAL_TANGENT_SPACE_ALIGNMENT >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_5838e5f0dd5ab947ad6c2a3e65bd02a7.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, LOCALITY_PRESERVING_PROJECTIONS >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_2bc90d71c38154a27f1af1bec01e8233.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, MULTIDIMENSIONAL_SCALING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_0e858271b41ce9ae214dd28cdc1ff08c.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, NEIGHBORHOOD_PRESERVING_EMBEDDING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_37dc403b78dd193f558e6c7413914ba0.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, PASS_THRU >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_82a0354a3b09fd6ac74958bb9ba48a15.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, PCA >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_3c2f2f5a6b8df1a90c4328038972d141.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, RANDOM_PROJECTION >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_a41d01f26e3b630ea0fbfe278169583e.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, STOCHASTIC_PROXIMITY_EMBEDDING >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_035998ee988a0c3d857f93d6aeecf13f.html", null ],
    [ "implementation< RandomAccessIterator, KernelCallback, DistanceCallback, FeatureVectorCallback, TSNE >", "structtapkee_1_1tapkee__internal_1_1implementation_3_01RandomAccessIterator_00_01KernelCallback_d12e0424b94539f9ffda430c58811d50.html", null ],
    [ "kernel_callback", "structkernel__callback.html", null ],
    [ "LoggerImplementation", "classtapkee_1_1LoggerImplementation.html", [
      [ "DefaultLoggerImplementation", "classtapkee_1_1DefaultLoggerImplementation.html", null ]
    ] ],
    [ "LoggingSingleton", "classtapkee_1_1LoggingSingleton.html", null ],
    [ "MethodTraits< method >", "structtapkee_1_1MethodTraits.html", null ],
    [ "missed_parameter_error", "classtapkee_1_1missed__parameter__error.html", null ],
    [ "neighbors_finder< RandomAccessIterator >", "structneighbors__finder.html", null ],
    [ "node< P >", "structtapkee_1_1tapkee__internal_1_1node.html", null ],
    [ "VpTree< T, distance >::Node", "structtsne_1_1VpTree_1_1Node.html", null ],
    [ "not_enough_memory_error", "classtapkee_1_1not__enough__memory__error.html", null ],
    [ "OptionGroup", "classez_1_1OptionGroup.html", null ],
    [ "pimpl_distance_callback< Implementation >", "structpimpl__distance__callback.html", null ],
    [ "pimpl_kernel_callback< Implementation >", "structpimpl__kernel__callback.html", null ],
    [ "precomputed_distance_callback", "structprecomputed__distance__callback.html", null ],
    [ "precomputed_kernel_callback", "structprecomputed__kernel__callback.html", null ],
    [ "ProjectingFunction", "structtapkee_1_1ProjectingFunction.html", null ],
    [ "ProjectingFunction", "structtapkee_1_1tapkee_1_1ProjectingFunction.html", null ],
    [ "ProjectionImplementation", "structtapkee_1_1ProjectionImplementation.html", null ],
    [ "ProjectionImplementation", "structtapkee_1_1tapkee_1_1ProjectionImplementation.html", [
      [ "MatrixProjectionImplementation", "structtapkee_1_1MatrixProjectionImplementation.html", null ],
      [ "MatrixProjectionImplementation", "structtapkee_1_1tapkee_1_1MatrixProjectionImplementation.html", null ]
    ] ],
    [ "QuadTree", "classtsne_1_1QuadTree.html", null ],
    [ "SparseInverseMatrixOperation", "structtapkee_1_1tapkee__internal_1_1SparseInverseMatrixOperation.html", null ],
    [ "timed_context", "structtapkee_1_1tapkee__internal_1_1timed__context.html", null ],
    [ "Triplet< T >", "structtapkee_1_1tapkee__internal_1_1Triplet.html", null ],
    [ "TSNE", "classtsne_1_1TSNE.html", null ],
    [ "unsupported_method_error", "classtapkee_1_1unsupported__method__error.html", null ],
    [ "v_array< T >", "classtapkee_1_1tapkee__internal_1_1v__array.html", null ],
    [ "VpTree< T, distance >", "classtsne_1_1VpTree.html", null ],
    [ "wrong_parameter_error", "classtapkee_1_1wrong__parameter__error.html", null ]
];